<?PHP
code::init();
code::initFunction("Insere(INFO)");
code::l("novo,anterior,leitor : EstruturaLista;", "Declarando cursores e novo elemento");
code::l("leitor := Lista;", "Inicializando o cursor no primeiro elemento");
code::l("novo := alocar();", "Alocando novo elemento");
code::l("novo.info := INFO;", "Atribuindo o valor ao novo elemento");
code::l("novo.proximo := nulo;", "Definindo o próximo elemento como nulo");
code::l();
code::l("Enquanto leitor != nulo e leitor.info < INFO faça", "Percorrendo elementos da lista para buscar a posição correta");
code::begin();
    code::l("anterior := leitor;", "Cursor 'anterior' aponta para o atual elemento da leitura");
    code::l("leilor := leitor.proximo;", "Cursor 'leitor' aponta para o próximo elemento da leitura");
code::end();
code::l();
code::l("Se leitor != nulo então", "Inserindo numa posição diferente da última");
code::begin();
    code::l("Se anterior == nulo então", "Inserindo na primeira posição");
    code::begin();
        code::l("novo.proximo := Lista;","");
        code::l("Lista := novo;","Novo primeiro elemento da lista");
    code::end();
    code::l("Senão", "Inserindo em posição intermediária");
    code::begin();
        code::l("anterior.proximo := novo;","");
        code::l("novo.proximo := leitor;","");
    code::end();
code::end();
code::l("Senão", "Inserindo na última posição");
code::begin();
    code::l("Se anterior == nulo então", "Inserindo o primeiro elemento");
    code::begin();
        code::l("Lista := novo;","");
    code::end();
    code::l("Senão", "Inserindo na última posição");
    code::begin();
        code::l("anterior.proximo := novo;","");
    code::end();
code::end();

code::write();