<?PHP 
code::init();
code::initFunction("Remove(Linha,Coluna)");

code::l("leitorLinha,anteriorLinha : NoLista;","Declarando variável para a leitura da linha");
code::l("leitorColuna,anteriorColuna : NoLista;","Declarando variável para a leitura da coluna");
code::l();
code::l("leitorLinha := Linhas[Linha];","Variável de leitura posicionado no início da linha");
code::l();
code::l("Enquanto leitorLinha != nulo e leitorLinha.coluna != Coluna faça","Percorrendo colunas que cruzam com a linha até encontrar a coluna do elemento");
code::begin();
    code::l("anteriorLinha := leitorLinha;","Armazenando elemento atual");
    code::l("leitorLinha := leitorLinha.direita;","Leitor avança para o elemento a direita na linha");
code::end();
code::l();
code::l("Se leitorLinha != nulo então", "Caso o elemento de remoção for encontrado");
code::begin();
    code::l("leitorColuna := Colunas[Coluna];","Posicionando leitor no topo da coluna de remoção");
    code::l();
    code::l("Enquanto leitorColuna != leitorLinha faça", "Percorrendo colunas que cruzam com a linha até encontrar a coluna do elemento");
    code::begin();
        code::l("anteriorColuna := leitorColuna;","Armazenando elemento atual");
        code::l("leitorColuna := leitorColuna.abaixo;","Leitor avança para o elemento abaixo na coluna");
    code::end();
    code::l();
    code::l("Se anteriorLinha != nulo então", "Caso não for o primeiro elemento da linha");
    code::begin();
        code::l("anteriorLinha.direita := leitorLinha.direita;","Elemento anterior da linha aponta para o próximo");
    code::end();
    code::l("Senão","Caso for o primeiro elemento da linha");
    code::begin();
        code::l("Linhas[Linha] := leitorLinha.direita;","Novo primeiro elemento da linha é definido");
    code::end();
    code::l();
    code::l("Se anteriorColuna != nulo então","Caso não for o primeiro elemento da coluna");
    code::begin();
        code::l("anteriorColuna.abaixo := leitorColuna.abaixo;","Elemento anterior da coluna aponta para o próximo");
    code::end();
    code::l("Senão","Caso for o primeiro elemento da linha");
    code::begin();
        code::l("Colunas[Coluna] := leitorColuna.abaixo;","Novo primeiro elemento da linha é definido");
    code::end();
code::end();
code::write();