-- MySQL Script generated by MySQL Workbench
-- 02/11/16 13:57:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Cadilag
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Cadilag` ;

-- -----------------------------------------------------
-- Schema Cadilag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cadilag` DEFAULT CHARACTER SET utf8 ;
USE `Cadilag` ;

-- -----------------------------------------------------
-- Table `Cadilag`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_fname` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) BINARY NOT NULL,
  `usu_lname` VARCHAR(100) NULL,
  `usu_nickname` VARCHAR(100) NULL,
  `last_login_date` DATE NULL,
  `last_login_hour` TIME NULL,
  `dia_cadastro` DATE NULL,
  PRIMARY KEY (`usu_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Professor` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Professor` (
  `prof_id` INT NOT NULL,
  `prof_confirmado` TINYINT(1) NULL,
  PRIMARY KEY (`prof_id`),
  INDEX `fk_Professor_Usuario1_idx` (`prof_id` ASC),
  CONSTRAINT `fk_Professor_Usuario1`
    FOREIGN KEY (`prof_id`)
    REFERENCES `Cadilag`.`Usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Instituicao` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Instituicao` (
  `inst_id` INT NOT NULL AUTO_INCREMENT,
  `inst_nome` VARCHAR(100) NOT NULL,
  `inst_uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`inst_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Curso` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Curso` (
  `cur_id` INT NOT NULL AUTO_INCREMENT,
  `cur_nome` VARCHAR(100) NOT NULL,
  `cur_sigla` VARCHAR(5) NOT NULL,
  `inst_id` INT NOT NULL,
  PRIMARY KEY (`cur_id`),
  INDEX `fk_Curso_Instituicao1_idx` (`inst_id` ASC),
  CONSTRAINT `fk_Curso_Instituicao1`
    FOREIGN KEY (`inst_id`)
    REFERENCES `Cadilag`.`Instituicao` (`inst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Disciplina` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Disciplina` (
  `disc_id` INT NOT NULL AUTO_INCREMENT,
  `disc_nome` VARCHAR(100) NOT NULL,
  `cur_id` INT NOT NULL,
  PRIMARY KEY (`disc_id`),
  INDEX `fk_Disciplina_Curso1_idx` (`cur_id` ASC),
  CONSTRAINT `fk_Disciplina_Curso1`
    FOREIGN KEY (`cur_id`)
    REFERENCES `Cadilag`.`Curso` (`cur_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Turma` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Turma` (
  `tur_ano` INT NOT NULL,
  `tur_semestre` INT NOT NULL,
  `prof_id` INT NULL,
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `disc_id` INT NULL,
  INDEX `fk_Turma_Professor1_idx` (`prof_id` ASC),
  PRIMARY KEY (`idTurma`),
  INDEX `fk_Turma_Disciplina1_idx` (`disc_id` ASC),
  CONSTRAINT `fk_Turma_Professor1`
    FOREIGN KEY (`prof_id`)
    REFERENCES `Cadilag`.`Professor` (`prof_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Turma_Disciplina1`
    FOREIGN KEY (`disc_id`)
    REFERENCES `Cadilag`.`Disciplina` (`disc_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Aluno` (
  `alu_id` INT NOT NULL,
  `idTurma` INT NULL,
  INDEX `fk_Aluno_Usuario1_idx` (`alu_id` ASC),
  UNIQUE INDEX `alu_id_UNIQUE` (`alu_id` ASC),
  PRIMARY KEY (`alu_id`),
  INDEX `fk_Aluno_Turma1_idx` (`idTurma` ASC),
  CONSTRAINT `fk_Aluno_Usuario1`
    FOREIGN KEY (`alu_id`)
    REFERENCES `Cadilag`.`Usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Aluno_Turma1`
    FOREIGN KEY (`idTurma`)
    REFERENCES `Cadilag`.`Turma` (`idTurma`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Tipo_Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Tipo_Permissao` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Tipo_Permissao` (
  `tper_nome` VARCHAR(45) NOT NULL,
  `tper_value` INT NOT NULL,
  PRIMARY KEY (`tper_value`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Estrutura_De_Dado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Estrutura_De_Dado` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Estrutura_De_Dado` (
  `ed_id` INT NOT NULL,
  `ed_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ed_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Permissoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Permissoes` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Permissoes` (
  `ed_id` INT NOT NULL,
  `permisao_id` INT NOT NULL AUTO_INCREMENT,
  `Turma_idTurma` INT NOT NULL,
  INDEX `fk_Grupo_has_Estrutura_De_Dado_Estrutura_De_Dado1_idx` (`ed_id` ASC),
  PRIMARY KEY (`permisao_id`),
  INDEX `fk_Permissoes_Turma1_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Grupo_has_Estrutura_De_Dado_Estrutura_De_Dado1`
    FOREIGN KEY (`ed_id`)
    REFERENCES `Cadilag`.`Estrutura_De_Dado` (`ed_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Permissoes_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `Cadilag`.`Turma` (`idTurma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Atividade` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Atividade` (
  `atv_id` INT NOT NULL AUTO_INCREMENT,
  `atv_data_limite` DATE NOT NULL,
  `idTurma` INT NULL,
  `atv_titulo` VARCHAR(45) NOT NULL,
  `atv_texto` LONGTEXT NOT NULL,
  `atv_data` DATE NULL,
  `atv_hora` TIME NULL,
  `atv_tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`atv_id`),
  INDEX `fk_Atividade_Turma1_idx` (`idTurma` ASC),
  CONSTRAINT `fk_Atividade_Turma1`
    FOREIGN KEY (`idTurma`)
    REFERENCES `Cadilag`.`Turma` (`idTurma`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Arquivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Arquivo` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Arquivo` (
  `descricao` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(100) NOT NULL,
  `arq_id` INT NOT NULL,
  `idusuario` INT NULL,
  `caminho` VARCHAR(100) NULL,
  `idatividade` INT NOT NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  INDEX `fk_Arquivo_Usuario1_idx` (`idusuario` ASC),
  PRIMARY KEY (`arq_id`),
  INDEX `fk_Arquivo_Atividade1_idx` (`idatividade` ASC),
  CONSTRAINT `fk_Arquivo_Usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `Cadilag`.`Usuario` (`usu_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Arquivo_Atividade1`
    FOREIGN KEY (`idatividade`)
    REFERENCES `Cadilag`.`Atividade` (`atv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Topico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Topico` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Topico` (
  `top_id` INT NOT NULL AUTO_INCREMENT,
  `top_assunto` VARCHAR(100) NOT NULL,
  `usu_id` INT NULL,
  `topico_texto` LONGTEXT NOT NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`top_id`),
  INDEX `fk_Topico_Usuario1_idx` (`usu_id` ASC),
  CONSTRAINT `fk_Topico_Usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `Cadilag`.`Usuario` (`usu_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Resposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Resposta` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Resposta` (
  `resp_id` INT NOT NULL AUTO_INCREMENT,
  `resp_texto` LONGTEXT NOT NULL,
  `top_id` INT NULL,
  `usu_id` INT NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`resp_id`),
  INDEX `fk_Resposta_Topico2_idx` (`top_id` ASC),
  INDEX `fk_Resposta_Usuario1_idx` (`usu_id` ASC),
  CONSTRAINT `fk_Resposta_Topico2`
    FOREIGN KEY (`top_id`)
    REFERENCES `Cadilag`.`Topico` (`top_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Resposta_Usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `Cadilag`.`Usuario` (`usu_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Configuracoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Configuracoes` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Configuracoes` (
  `Usuario_usu_id` INT NOT NULL,
  `Path_imguser` VARCHAR(100) NULL,
  `Path_imgcover` VARCHAR(100) NULL,
  `cssImgCover` VARCHAR(100) NULL,
  INDEX `fk_Configuracoes_Usuario1_idx` (`Usuario_usu_id` ASC),
  PRIMARY KEY (`Usuario_usu_id`),
  UNIQUE INDEX `Usuario_usu_id_UNIQUE` (`Usuario_usu_id` ASC),
  CONSTRAINT `fk_Configuracoes_Usuario1`
    FOREIGN KEY (`Usuario_usu_id`)
    REFERENCES `Cadilag`.`Usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Permissoes_has_Tipo_Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Permissoes_has_Tipo_Permissao` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Permissoes_has_Tipo_Permissao` (
  `Permissoes_permisao_id` INT NOT NULL,
  `Tipo_Permissao_tper_value` INT NOT NULL,
  PRIMARY KEY (`Permissoes_permisao_id`, `Tipo_Permissao_tper_value`),
  INDEX `fk_Permissoes_has_Tipo_Permissao_Tipo_Permissao1_idx` (`Tipo_Permissao_tper_value` ASC),
  INDEX `fk_Permissoes_has_Tipo_Permissao_Permissoes1_idx` (`Permissoes_permisao_id` ASC),
  CONSTRAINT `fk_Permissoes_has_Tipo_Permissao_Permissoes1`
    FOREIGN KEY (`Permissoes_permisao_id`)
    REFERENCES `Cadilag`.`Permissoes` (`permisao_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Permissoes_has_Tipo_Permissao_Tipo_Permissao1`
    FOREIGN KEY (`Tipo_Permissao_tper_value`)
    REFERENCES `Cadilag`.`Tipo_Permissao` (`tper_value`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`EntradaProgramada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`EntradaProgramada` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`EntradaProgramada` (
  `idEntradaProgramada` INT NOT NULL AUTO_INCREMENT,
  `Usuario_usu_id` INT NOT NULL,
  `Estrutura_De_Dado_ed_id` INT NOT NULL,
  `EntradaProgramadacol` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`idEntradaProgramada`),
  INDEX `fk_EntradaProgramada_Usuario1_idx` (`Usuario_usu_id` ASC),
  INDEX `fk_EntradaProgramada_Estrutura_De_Dado1_idx` (`Estrutura_De_Dado_ed_id` ASC),
  CONSTRAINT `fk_EntradaProgramada_Usuario1`
    FOREIGN KEY (`Usuario_usu_id`)
    REFERENCES `Cadilag`.`Usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EntradaProgramada_Estrutura_De_Dado1`
    FOREIGN KEY (`Estrutura_De_Dado_ed_id`)
    REFERENCES `Cadilag`.`Estrutura_De_Dado` (`ed_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`Ep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`Ep` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`Ep` (
  `idep` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `type` TINYINT(1) NOT NULL DEFAULT 1,
  `EntradaProgramada_idEntradaProgramada` INT NOT NULL,
  PRIMARY KEY (`idep`),
  INDEX `fk_ep_EntradaProgramada1_idx` (`EntradaProgramada_idEntradaProgramada` ASC),
  CONSTRAINT `fk_ep_EntradaProgramada1`
    FOREIGN KEY (`EntradaProgramada_idEntradaProgramada`)
    REFERENCES `Cadilag`.`EntradaProgramada` (`idEntradaProgramada`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadilag`.`solicitacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadilag`.`solicitacao` ;

CREATE TABLE IF NOT EXISTS `Cadilag`.`solicitacao` (
  `Aluno_alu_id` INT NOT NULL,
  `Turma_idTurma` INT NOT NULL,
  `idsolicitacao` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_solicitacao_Aluno1_idx` (`Aluno_alu_id` ASC),
  INDEX `fk_solicitacao_Turma1_idx` (`Turma_idTurma` ASC),
  PRIMARY KEY (`idsolicitacao`),
  CONSTRAINT `fk_solicitacao_Aluno1`
    FOREIGN KEY (`Aluno_alu_id`)
    REFERENCES `Cadilag`.`Aluno` (`alu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `Cadilag`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
